// <auto-generated />
using Aquino_MartizanoFinals.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Aquino_MartizanoFinals.Migrations
{
    [DbContext(typeof(Aquino_MartizanoFinalsContext))]
    partial class Aquino_MartizanoFinalsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Aquino_MartizanoFinals.Models.User", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Week1")
                        .HasColumnType("int");

                    b.Property<int>("Week2")
                        .HasColumnType("int");

                    b.Property<int>("Week3")
                        .HasColumnType("int");

                    b.HasKey("StudentId");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
